ex1 = "XJ/yvFLssM/MDvfN0Al5EQthRLGZ6vO9f3yssoa/kg8="
ex2 = "Bcy/o2lljJ3bVlIisofo7FH+42TuSzItsuafp1oWhOA="
ex3 = "rlJWV2FOOfnqE/Uep4GnYfXQSozgxxr1f4k4hymtwp0="
ex4 = "kbWWGnNkuG6dbacT+d1I7rBFhtOK2zIVLdR0QJzwwK0="