ex1 = "Rlv2svHhbx9+C2sWWtJ3rNRVhYQ+qy/9Lrdth8+kiOY="
ex2 = "XNXGBXw6SyhacVhrpNBELmHD/kfrEFnlGkzbn6P/dE0="
ex3 = "Og/8rJID8ul/4gcb10El7C/sDUf1CGP88QtfyPBKwOk="
ex4 = "WuwWT7nkjotFXtW0XcQP9i40sdEq5HDD9XroF/VdS1U="
ex5 = ""