ex1 = "uZGlNPBo2fndwd0jQKlMhJcKSsl7T0cbMAyYs/7BwOY="
ex2 = "lxlMrKRhAHmUo2hl75ZpZO9VhncFDR4FpWXiXIw72eE="
ex3 = "EPpKi434W8ag5XhNhpu2fQO3aaY84OHhXwuFu7fcfsE="
ex4a = "KYzzjMsc6s6z7Wpk67AY2wVZ2Fd5UdIg0Hbly2GeYyU="
ex4b = "i2MbE73Te72IJ1RvwdaJsEXYvGJW8u4IsbsGqLocLTM="