ex1a = "Y5F4VKVM0GB920DLkrNFv6Ma/GFXPoemRom9Xn+xzIc="
ex1b = "xOIY/LXWKtNX4Pk7TaQleIl3tv8ZXsdWBuwq+op9/qA="
ex1c = "WR95zg9jZtW+8zZ2TDZH0L/wZ04ViFB4ntgWXv3lo3c="
ex2a = "jy/08PpgzxXYriGIn1w/Ax8tLsaHgNKuNIo5Ln9WANM="
ex2b = "+FE7BFesLS3NKmWUS8SwwEOqCzmhRaAi8SIKD6DluTg="
ex2c = "Zdw2y0UlEAMBms1Fn7cjtbPZu+Fit0LuqSb3YjESKCo="
ex3a = "tFcCUr5mNNwBDtSbtVwAaERYbIbnIYdciIix7aiYgg4="
ex3b = "DpvAJtKIcvTersLsgQf02+RtvMfbDHIfg4fHHC2eHTU="