ex1 = "r6cmQQHNLhtGM80E9tPF249yInVEG7BLgIH7v/ji+UI="
ex2 = "cmjWPRyjftMYsLhBLVb7asZQh0ljoa6eOe7J4W/o6x0="
ex3a = "iCR/p5AknoDjy88nDjn0hEvZmaSDqtmElYgVsfFK+CU="
ex3b = "sO9Np8dQKXKLWADvLslMekCji/oTUBrvPJI+ogh0QhI="